# Simple Makefile for AFL++ Scheduler

CC = gcc
CFLAGS = -Wall -Werror -O2
LDFLAGS = -lbpf -lelf -lm

all: afl_monitor_param afl_sched_loader_param

afl_monitor_param: afl_monitor_param.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

afl_sched_loader_param: afl_sched_loader_param.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

clean:
	rm -f afl_monitor_param afl_sched_loader_param

.PHONY: all clean
