/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __AFL_EBPF_EXECVE_SKEL_H__
#define __AFL_EBPF_EXECVE_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct afl_ebpf_execve {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *fuzzer_pid;
		struct bpf_map *exec_count;
	} maps;
	struct {
		struct bpf_program *trace_execve_enter;
	} progs;
	struct {
		struct bpf_link *trace_execve_enter;
	} links;

#ifdef __cplusplus
	static inline struct afl_ebpf_execve *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct afl_ebpf_execve *open_and_load();
	static inline int load(struct afl_ebpf_execve *skel);
	static inline int attach(struct afl_ebpf_execve *skel);
	static inline void detach(struct afl_ebpf_execve *skel);
	static inline void destroy(struct afl_ebpf_execve *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
afl_ebpf_execve__destroy(struct afl_ebpf_execve *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
afl_ebpf_execve__create_skeleton(struct afl_ebpf_execve *obj);

static inline struct afl_ebpf_execve *
afl_ebpf_execve__open_opts(const struct bpf_object_open_opts *opts)
{
	struct afl_ebpf_execve *obj;
	int err;

	obj = (struct afl_ebpf_execve *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = afl_ebpf_execve__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	afl_ebpf_execve__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct afl_ebpf_execve *
afl_ebpf_execve__open(void)
{
	return afl_ebpf_execve__open_opts(NULL);
}

static inline int
afl_ebpf_execve__load(struct afl_ebpf_execve *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct afl_ebpf_execve *
afl_ebpf_execve__open_and_load(void)
{
	struct afl_ebpf_execve *obj;
	int err;

	obj = afl_ebpf_execve__open();
	if (!obj)
		return NULL;
	err = afl_ebpf_execve__load(obj);
	if (err) {
		afl_ebpf_execve__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
afl_ebpf_execve__attach(struct afl_ebpf_execve *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
afl_ebpf_execve__detach(struct afl_ebpf_execve *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *afl_ebpf_execve__elf_bytes(size_t *sz);

static inline int
afl_ebpf_execve__create_skeleton(struct afl_ebpf_execve *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "afl_ebpf_execve";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 2;
	s->map_skel_sz = 24;
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt,
			sizeof(*s->maps) > 24 ? sizeof(*s->maps) : 24);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	map = (struct bpf_map_skeleton *)((char *)s->maps + 0 * s->map_skel_sz);
	map->name = "fuzzer_pid";
	map->map = &obj->maps.fuzzer_pid;

	map = (struct bpf_map_skeleton *)((char *)s->maps + 1 * s->map_skel_sz);
	map->name = "exec_count";
	map->map = &obj->maps.exec_count;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "trace_execve_enter";
	s->progs[0].prog = &obj->progs.trace_execve_enter;
	s->progs[0].link = &obj->links.trace_execve_enter;

	s->data = afl_ebpf_execve__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *afl_ebpf_execve__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x28\x0a\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0d\0\
\x01\0\xb7\x01\0\0\0\0\0\0\x63\x1a\xfc\xff\0\0\0\0\x85\0\0\0\x0e\0\0\0\xbf\x06\
\0\0\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xfc\xff\xff\xff\x18\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\x15\0\x0b\0\0\0\0\0\x77\x06\0\0\x20\0\0\
\0\x61\x01\0\0\0\0\0\0\x5d\x61\x08\0\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\
\xfc\xff\xff\xff\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\x15\0\
\x02\0\0\0\0\0\xb7\x01\0\0\x01\0\0\0\xdb\x10\0\0\0\0\0\0\xb7\0\0\0\0\0\0\0\x95\
\0\0\0\0\0\0\0\x47\x50\x4c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x74\x02\0\0\x74\x02\0\0\xbf\x02\0\0\0\
\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\
\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x02\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\
\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x08\0\0\0\x19\0\0\0\0\0\0\x08\x09\0\0\0\x1f\
\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\0\0\0\0\x04\0\
\0\x04\x20\0\0\0\x2c\0\0\0\x01\0\0\0\0\0\0\0\x31\0\0\0\x05\0\0\0\x40\0\0\0\x3d\
\0\0\0\x07\0\0\0\x80\0\0\0\x41\0\0\0\x0a\0\0\0\xc0\0\0\0\x47\0\0\0\0\0\0\x0e\
\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x0e\0\0\0\x52\0\0\0\0\0\0\x08\x0f\0\0\0\
\x58\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\x2c\0\0\
\0\x01\0\0\0\0\0\0\0\x31\0\0\0\x05\0\0\0\x40\0\0\0\x3d\0\0\0\x07\0\0\0\x80\0\0\
\0\x41\0\0\0\x0d\0\0\0\xc0\0\0\0\x6b\0\0\0\0\0\0\x0e\x10\0\0\0\x01\0\0\0\0\0\0\
\0\0\0\0\x02\x13\0\0\0\x76\0\0\0\x05\0\0\x04\x28\0\0\0\x91\0\0\0\x0e\0\0\0\0\0\
\0\0\x98\0\0\0\x08\0\0\0\x40\0\0\0\xa5\0\0\0\x14\0\0\0\x80\0\0\0\xae\0\0\0\x17\
\0\0\0\xc0\0\0\0\xb3\0\0\0\x17\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\x02\x15\0\0\0\0\0\
\0\0\0\0\0\x0a\x16\0\0\0\xb8\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\0\
\0\x02\x18\0\0\0\0\0\0\0\0\0\0\x0a\x14\0\0\0\0\0\0\0\x01\0\0\x0d\x02\0\0\0\xbd\
\0\0\0\x12\0\0\0\xc1\0\0\0\x01\0\0\x0c\x19\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x16\
\0\0\0\x04\0\0\0\x04\0\0\0\xa9\x02\0\0\0\0\0\x0e\x1b\0\0\0\x01\0\0\0\xb1\x02\0\
\0\x02\0\0\x0f\0\0\0\0\x0c\0\0\0\0\0\0\0\x20\0\0\0\x11\0\0\0\0\0\0\0\x20\0\0\0\
\xb7\x02\0\0\x01\0\0\x0f\0\0\0\0\x1c\0\0\0\0\0\0\0\x04\0\0\0\0\x69\x6e\x74\0\
\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\
\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x74\
\x79\x70\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\
\x61\x6c\x75\x65\0\x66\x75\x7a\x7a\x65\x72\x5f\x70\x69\x64\0\x5f\x5f\x75\x36\
\x34\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\
\0\x65\x78\x65\x63\x5f\x63\x6f\x75\x6e\x74\0\x73\x79\x73\x63\x61\x6c\x6c\x73\
\x5f\x65\x6e\x74\x65\x72\x5f\x65\x78\x65\x63\x76\x65\x5f\x61\x72\x67\x73\0\x75\
\x6e\x75\x73\x65\x64\0\x5f\x5f\x73\x79\x73\x63\x61\x6c\x6c\x5f\x6e\x72\0\x66\
\x69\x6c\x65\x6e\x61\x6d\x65\0\x61\x72\x67\x76\0\x65\x6e\x76\x70\0\x63\x68\x61\
\x72\0\x63\x74\x78\0\x74\x72\x61\x63\x65\x5f\x65\x78\x65\x63\x76\x65\x5f\x65\
\x6e\x74\x65\x72\0\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\x73\x63\
\x61\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x65\x78\x65\x63\
\x76\x65\0\x2f\x68\x6f\x6d\x65\x2f\x65\x72\x6e\x65\x73\x74\x6f\x2f\x44\x6f\x63\
\x75\x6d\x65\x6e\x74\x73\x2f\x41\x46\x4c\x70\x6c\x75\x73\x70\x6c\x75\x73\x2f\
\x73\x72\x63\x2f\x61\x66\x6c\x2d\x65\x62\x70\x66\x2d\x65\x78\x65\x63\x76\x65\
\x2e\x63\0\x69\x6e\x74\x20\x74\x72\x61\x63\x65\x5f\x65\x78\x65\x63\x76\x65\x5f\
\x65\x6e\x74\x65\x72\x28\x73\x74\x72\x75\x63\x74\x20\x73\x79\x73\x63\x61\x6c\
\x6c\x73\x5f\x65\x6e\x74\x65\x72\x5f\x65\x78\x65\x63\x76\x65\x5f\x61\x72\x67\
\x73\x20\x2a\x63\x74\x78\x29\x20\x7b\0\x20\x20\x20\x20\x5f\x5f\x75\x33\x32\x20\
\x6b\x65\x79\x20\x3d\x20\x30\x3b\0\x20\x20\x20\x20\x69\x6e\x74\x20\x70\x70\x69\
\x64\x20\x3d\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\
\x5f\x70\x69\x64\x5f\x74\x67\x69\x64\x28\x29\x20\x3e\x3e\x20\x33\x32\x3b\0\x20\
\x20\x20\x20\x69\x6e\x74\x20\x2a\x66\x75\x7a\x7a\x5f\x70\x69\x64\x20\x3d\x20\
\x62\x70\x66\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\x65\x6c\x65\x6d\
\x28\x26\x66\x75\x7a\x7a\x65\x72\x5f\x70\x69\x64\x2c\x20\x26\x6b\x65\x79\x29\
\x3b\0\x20\x20\x20\x20\x69\x66\x20\x28\x21\x66\x75\x7a\x7a\x5f\x70\x69\x64\x29\
\x20\x72\x65\x74\x75\x72\x6e\x20\x30\x3b\0\x20\x20\x20\x20\x69\x66\x20\x28\x70\
\x70\x69\x64\x20\x3d\x3d\x20\x2a\x66\x75\x7a\x7a\x5f\x70\x69\x64\x29\x20\x7b\0\
\x20\x20\x20\x20\x20\x20\x20\x20\x63\x6f\x75\x6e\x74\x20\x3d\x20\x62\x70\x66\
\x5f\x6d\x61\x70\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\x65\x6c\x65\x6d\x28\x26\x65\
\x78\x65\x63\x5f\x63\x6f\x75\x6e\x74\x2c\x20\x26\x6b\x65\x79\x29\x3b\0\x20\x20\
\x20\x20\x20\x20\x20\x20\x69\x66\x20\x28\x63\x6f\x75\x6e\x74\x29\x20\x7b\0\x20\
\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x20\x5f\x5f\x73\x79\x6e\x63\x5f\x66\
\x65\x74\x63\x68\x5f\x61\x6e\x64\x5f\x61\x64\x64\x28\x63\x6f\x75\x6e\x74\x2c\
\x20\x31\x29\x3b\0\x7d\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x6d\x61\x70\x73\0\
\x6c\x69\x63\x65\x6e\x73\x65\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\
\0\0\0\xdc\0\0\0\xf0\0\0\0\0\0\0\0\x08\0\0\0\xd4\0\0\0\x01\0\0\0\0\0\0\0\x1a\0\
\0\0\x10\0\0\0\xd4\0\0\0\x0d\0\0\0\0\0\0\0\xf9\0\0\0\x33\x01\0\0\0\xa0\0\0\x08\
\0\0\0\xf9\0\0\0\x74\x01\0\0\x0b\xa4\0\0\x10\0\0\0\xf9\0\0\0\x87\x01\0\0\x10\
\xb8\0\0\x28\0\0\0\xf9\0\0\0\x74\x01\0\0\x0b\xa4\0\0\x30\0\0\0\xf9\0\0\0\xb8\
\x01\0\0\x15\xc8\0\0\x48\0\0\0\xf9\0\0\0\xf4\x01\0\0\x09\xcc\0\0\x50\0\0\0\xf9\
\0\0\0\x87\x01\0\0\x2b\xb8\0\0\x58\0\0\0\xf9\0\0\0\x11\x02\0\0\x11\xd8\0\0\x60\
\0\0\0\xf9\0\0\0\x11\x02\0\0\x09\xd8\0\0\x70\0\0\0\xf9\0\0\0\x2e\x02\0\0\x11\
\xdc\0\0\x90\0\0\0\xf9\0\0\0\x66\x02\0\0\x0d\xe0\0\0\xa0\0\0\0\xf9\0\0\0\x7b\
\x02\0\0\x0d\xe4\0\0\xa8\0\0\0\xf9\0\0\0\xa7\x02\0\0\x01\xf8\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\xa3\0\0\0\0\0\x03\0\xa8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x25\0\0\
\0\x12\0\x03\0\0\0\0\0\0\0\0\0\xb8\0\0\0\0\0\0\0\x77\0\0\0\x11\0\x06\0\0\0\0\0\
\0\0\0\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x11\0\x06\0\x20\0\0\0\0\0\0\0\x20\0\0\0\0\
\0\0\0\x9b\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x30\0\0\0\0\0\0\
\0\x01\0\0\0\x04\0\0\0\x78\0\0\0\0\0\0\0\x01\0\0\0\x05\0\0\0\x60\x02\0\0\0\0\0\
\0\x04\0\0\0\x04\0\0\0\x6c\x02\0\0\0\0\0\0\x04\0\0\0\x05\0\0\0\x84\x02\0\0\0\0\
\0\0\x04\0\0\0\x06\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x90\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xa0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xb0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xc0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xd0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xe0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xf0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\0\x01\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x0c\x0f\x0d\x0e\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\
\x2e\x42\x54\x46\x2e\x65\x78\x74\0\x65\x78\x65\x63\x5f\x63\x6f\x75\x6e\x74\0\
\x2e\x6d\x61\x70\x73\0\x74\x72\x61\x63\x65\x5f\x65\x78\x65\x63\x76\x65\x5f\x65\
\x6e\x74\x65\x72\0\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x2e\
\x72\x65\x6c\x74\x72\x61\x63\x65\x70\x6f\x69\x6e\x74\x2f\x73\x79\x73\x63\x61\
\x6c\x6c\x73\x2f\x73\x79\x73\x5f\x65\x6e\x74\x65\x72\x5f\x65\x78\x65\x63\x76\
\x65\0\x6c\x69\x63\x65\x6e\x73\x65\0\x66\x75\x7a\x7a\x65\x72\x5f\x70\x69\x64\0\
\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\
\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\x53\x45\0\x4c\x42\x42\x30\x5f\x34\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x82\0\0\0\x03\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x7c\x09\0\0\0\0\0\0\xaa\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\x4a\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\
\0\0\0\0\0\xb8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x46\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\x08\0\0\0\0\0\0\x20\
\0\0\0\0\0\0\0\x0c\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x6f\0\0\
\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf8\0\0\0\0\0\0\0\x04\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1f\0\0\0\x01\0\0\0\x03\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x96\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\x40\x01\0\0\0\0\0\0\x4b\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x92\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x68\x08\0\0\0\0\0\0\x30\0\0\0\0\0\0\0\x0c\0\0\0\x07\0\0\0\x08\0\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x8c\x06\
\0\0\0\0\0\0\x10\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x07\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x98\x08\0\0\0\0\0\0\
\xe0\0\0\0\0\0\0\0\x0c\0\0\0\x09\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x38\
\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x78\x09\0\0\0\0\0\0\
\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x8a\0\0\0\
\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa0\x07\0\0\0\0\0\0\xa8\0\0\0\0\0\0\
\0\x01\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct afl_ebpf_execve *afl_ebpf_execve::open(const struct bpf_object_open_opts *opts) { return afl_ebpf_execve__open_opts(opts); }
struct afl_ebpf_execve *afl_ebpf_execve::open_and_load() { return afl_ebpf_execve__open_and_load(); }
int afl_ebpf_execve::load(struct afl_ebpf_execve *skel) { return afl_ebpf_execve__load(skel); }
int afl_ebpf_execve::attach(struct afl_ebpf_execve *skel) { return afl_ebpf_execve__attach(skel); }
void afl_ebpf_execve::detach(struct afl_ebpf_execve *skel) { afl_ebpf_execve__detach(skel); }
void afl_ebpf_execve::destroy(struct afl_ebpf_execve *skel) { afl_ebpf_execve__destroy(skel); }
const void *afl_ebpf_execve::elf_bytes(size_t *sz) { return afl_ebpf_execve__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
afl_ebpf_execve__assert(struct afl_ebpf_execve *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __AFL_EBPF_EXECVE_SKEL_H__ */
